### ISSUE TITLE
Not truely an issue but how about fpga target

### ISSUE THREAD

**Issue by newfrogg** [ourspalois/PinAIpple#3]
I have a SoC like your works (Accelerator as host beside the Ibex), how can I use the software (c code) if I have a FPGA targets. I found you didn't use debug module. Is the reason caused by integrating fraise & debug cant not use? Thanks.

**Comment by ourspalois** [comment]
I am not sure what you mean here. What I understand is you want to know how to program the I memory of your system on an FPGA. 
you have a few different options : 
- a debug module (you seem to be familiar with this)  
- an external (usually flash) memory. 
- or what I am doing here : compiling my executable in a rtl file describing the instruction memory. (I have a image gen program to do that in the sw directory) 

This approach is not a good one for anything remotely close to production, this platform was built to test Fraise, I chose it because I was unaware of a few things when I designed this, and I didn't have enough pins to afford adding a debug. 
but adding a debug module should be quite easy, and it's been done in ibex_demo_system I think.

**Comment by newfrogg** [comment]
Thanks for your reply @ourspalois, 

My approach is simply based on the ibex_demo_system root repository. I just wonder the behavior of the Fraise top module.

As the [root repo](https://github.com/lowRISC/ibex-demo-system), all components (except Ibex core & its Debug Module) are peripherals. So the code in /sw folder is the way the Core call to access them and all of it is set to devices (through bus_device_e enum). That's all I understand for now.

My question is you have Fraise_host as host && Fraise_device as host, /sw is still the code that core Ibex call to access the Fraise ? 

I wonder it because I believe only host can control device. ib

**Comment by ourspalois** [comment]
Sorry for the late response. 
Fraise is behavioral code for an NVM accelerator chip INTEGNANO developped. 
Fraise Host is a port for the accelerator to send request and write to peripherals without the ibex core. the point is I can have the core shut down and only run the accelerator in normal run conditions.

**Comment by newfrogg** [comment]
Hi, it took a month. Is is the code for [test_accel](https://github.com/ourspalois/PinAIpple/blob/master/sw/demo/test_fraise/main.c) work wells. I'm have written an acceleartor wrapper to (something like your fraise) but can test it truely. I wonder which branch is the most up-to-date code. Master or IDEM or big_chip.

**Comment by ourspalois** [comment]
Hi, the IEDM branch is the most up to date.
